services:
  sonarr:
    container_name: ${NAME}
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - ${PORT}:8989
    volumes:
      - ${VOLUME_CONFIG}:/config
      - ${VOLUME_DATA}:/data
    env_file:
      - .env
