services:
  qbittorrent:
    container_name: ${NAME}
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    ports:
      - ${PORT1}:8090
      - ${PORT2}:6881
      - ${PORT2}:6881/udp
    volumes:
      - ${VOLUME_CONFIG}:/config
      - ${VOLUME_DATA}:/data
    env_file:
      - .env
