services:
  speedtest-tracker:
    container_name: ${NAME}
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    ports:
      - ${PORT}:80
    volumes:
      - ${VOLUME_CONFIG}:/config
    env_file:
      - .env
