services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    ports:
      - 8097:80
    volumes:
      - /srv/containers/speedtest-tracker/config:/config
    env_file:
      - .env
