services:
  pihole:
    container_name: ${NAME}
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "${PORT1}:53/tcp"
      - "${PORT2}:53/udp"
      - "${PORT3}:80/tcp"
    env_file:
      - .env
    volumes:
      - ${VOLUME_ETC}:/etc/pihole


