services:
  nextcloud:
    container_name: ${NAME}
    image: lscr.io/linuxserver/nextcloud:latest
    restart: unless-stopped
    ports:
      - ${PORT}:443
    volumes:
      - ${VOLUME_CONFIG}:/config
      - ${VOLUME_DATA}:/data
      - ${VOLUME_DOWNLOADS}:/downloads
      - ${VOLUME_MEDIA}:/media

    env_file:
      - .env
