services:
  radarr:
    container_name: ${NAME}
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - ${PORT}:7878
    volumes:
      - ${VOLUME_CONFIG}:/config
      - ${VOLUME_DATA}:/data
    env_file:
      - .env
