services:
  linkding:
    container_name: ${NAME}
    image: sissbruecker/linkding:latest
    restart: unless-stopped
    ports:
      - 9091:9090
    volumes:
      - ${VOLUME_DATA}:/etc/linkding/data
    env_file:
      - .env
