services:
  vikunja:
    container_name: ${NAME}
    image: vikunja/vikunja:latest
    restart: unless-stopped
    ports:
      - ${PORT}:3456
    volumes:
      - ${VOLUME_FILES}:/app/vikunja/files
      - ${VOLUME_DB}:/db
    env_file:
      - .env
