services:
  tailscale:
    container_name: ${NAME}
    image: tailscale/tailscale:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    command: tailscaled --tun=userspace-networking
    volumes:
      - ${VOLUME_DATA}:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file:
      - .env

