services:
  jellyfin:
    container_name: ${NAME}
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    ports:
      - ${PORT1}:8096
      - ${PORT2}:7359/udp
      - ${PORT3}:1900/udp
    volumes:
      - ${VOLUME_CONFIG}:/config
      - ${VOLUME_MOVIES}:/data/movies
      - ${VOLUME_TV}:/data/tv
    env_file:
      - .env
