services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - /srv/containers/jellyfin/config:/config
      - /mnt/data/media/movies:/data/movies
      - /mnt/data/media/tv:/data/tv
    env_file:
      - .env
