services:
  portainer:
    container_name: ${NAME}
    image: portainer/portainer-ce:sts
    restart: unless-stopped
    ports:
      - ${PORT}:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    env_file:
      - .env

volumes:
  portainer_data:
    name: portainer_data
