services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    ports:
      - 6767:6767
    volumes:
      - /srv/containers/bazarr/config:/config
      - /mnt/data:/data
    env_file:
      - .env
