services:
  app:
    container_name: ${NAME}
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - ${PORT1}:80
      - ${PORT2}:81
      - ${PORT3}:443
    volumes:
      - ${VOLUME_DATA}:/data
      - ${VOLUME_LETSENCRYPT}:/etc/letsencrypt
    env_file: .env
